# Site Settings
title: Dukes Beachhouse Winelist
description: >-
  This is a rundown of the wine list for Duke's Beach House Maui.
  It's a work-in-progress so please be forgiving!
github_username: recondoyuk
baseurl: "/winelist"
# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - 'jekyll-timeago'


  # Collections
collections:
  list_pages:
      output: true
  style_pages:
    output: true
  wine_pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "style_pages"
    values:
      layout: "styles"
  - scope:
      path: ""
      type: "wine_pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "list_pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

jekyll-timeago:
  depth: 4