# Site Settings
title: Dukes Beachhouse Winelist
description: >-
  This is a rundown of the Winelist for Duke's Beachhouse Maui.
  It's a work-in-progress so please be forgiving!
github_username: recondoyuk

# Build settings
markdown: kramdown
remote-theme: pages-themes/leap-day@0.2.0
#plugins:
#- jekyll-remote-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# theme: jekyll-theme-leap-day