# Site Settings
title: Dukes Beachhouse Winelist
description: >-
  This is a rundown of the wine list for Duke's Beach House Maui.
  It's a work-in-progress so please be forgiving!
github_username: recondoyuk
url: "https://recondoyuk.github.io"
baseurl: "/winelist"
# Build settings
markdown: kramdown
#theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-timeago


  # Collections
collections:
  list_pages:
      output: true
  style_pages:
    output: true
  wine_pages:
    output: true

defaults:
  - scope:
      path: "style_pages"
      type: "style_pages"
    values:
      css: "style"
      layout: "styles"
  - scope:
      path: "wine_pages"
      type: "wine_pages"
    values:
      css: "style"
      layout: "default"
  - scope:
      path: "list_pages"
      type: "list_pages"
    values:
      css: "style"
      layout: "default"
  - scope:
      path: ""
    values:
      css: "style"
      layout: "default"

sass:
  sass_dir: "_sass"

jekyll_timeago:
  depth: 4
  threshold: 0

timezone: Pacific/Honolulu
