# Site Settings
title: Dukes Beachhouse Winelist
description: >-
  This is a rundown of the Winelist for Duke's Beachhouse Maui.
  It's a work-in-progress so please be forgiving!
github_username: recondoyuk

# Build settings
markdown: kramdown
<<<<<<< HEAD
theme: jekyll-theme-chirpy
=======
remote_theme: chirpy
>>>>>>> f75690c9f06923306fcebc708954db95931a0246
plugins:
  - jekyll-feed

theme: jekyll-theme-leap-day